[package]
name = "bindless"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1"
camera = {path = "../../lib/camera"}
cinder = {path = "../../lib/cinder"}
util = {path = "../../lib/util"}
scene = {path = "../../lib/scene"}
zero-copy-assets = {path = "../../lib/zero-copy-assets"}
sdl2 = { git = "https://github.com/Rust-SDL2/rust-sdl2", features = ["bundled", "raw-window-handle"] }
math = { git = "https://github.com/ArthurKValladares/Yet-Another-Math-Lib" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
rayon = "1.6.0"
rkyv = {version = "0.7.41", features = ["alloc", "validation"]}

[build-dependencies]
home = "0.5.3"
rust-shader-tools = { git = "https://github.com/ArthurKValladares/Rust-Shader-Tools" }

[profile.dev.package.zero-copy-assets]
opt-level = 3

[profile.dev.package.memmap2]
opt-level = 3

[profile.dev.package.rkyv]
opt-level = 3

[profile.dev.package.image]
opt-level = 3

[profile.dev.package.png]
opt-level = 3