[package]
name = "cinder"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1"
ash = {version = "0.37"}
ash-window = {version = "0.12.0"}
winit = "0.27"
thiserror = "1"
math = { git = "https://github.com/ArthurKValladares/Yet-Another-Math-Lib" }
util = { path = "../util" }
tracing = "0.1"
raw-window-handle = "0.5"
rkyv = { version = "0.7", features = ["validation"] }
#rust-shader-tools = { git = "https://github.com/ArthurKValladares/Rust-Shader-Tools", features = ["shader-structs"] }
rust-shader-tools = { path = "C:/Users/Arthur/Documents/projects/libs/rust-shader-tools", features = ["shader-structs"] }
num = "0.4.0"
bitflags = "1.3.2"