[package]
name = "cinder"
version = "0.1.0"
edition = "2021"

[features]
default = ["empty"]
empty = []
metal = []
vulkan = []

[dependencies]
thiserror = "1"
math = { git = "https://github.com/ArthurKValladares/Yet-Another-Math-Lib" }