[package]
name = "Cinder-Renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cinder = {path = "./cinder"}
util = {path = "./util"}
winit = "0.27"

[build-dependencies]
home = "0.5.3"
rust-shader-tools = { git = "https://github.com/ArthurKValladares/Rust-Shader-Tools" }