[workspace]
members = [
    "crates/bin/hello-triangle",
    "crates/bin/hello-cube",
    "crates/bin/texture",
    "crates/bin/ui",
    "crates/bin/mesh",
    "crates/bin/debug",
    "crates/bin/depth-image",
    "crates/lib/cinder",
]
