[package]
name = "cinder_renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
cinder = {path = "./cinder"}
ember = {path = "./ember"}
util = {path = "./util"}
scene = {path = "./scene"}
egui-integration = {path = "./egui-integration"}
camera = {path = "./camera"}
input = {path = "./input"}
winit = "0.27"
image = "0.24.3"
math = { git = "https://github.com/ArthurKValladares/Yet-Another-Math-Lib" }
cgmath = "0.18.0"
tracing = "0.1"
tracing-subscriber = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"

[build-dependencies]
home = "0.5.3"
rust-shader-tools = { git = "https://github.com/ArthurKValladares/Rust-Shader-Tools", features = ["shader-structs"] }