[package]
name = "egui-integration"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1"
cinder = {path = "../cinder"}
util = {path = "../util"}
egui = "0.20"
egui-winit = "0.20"
winit = "0.27"
math = { git = "https://github.com/ArthurKValladares/Yet-Another-Math-Lib" }