[package]
name = "texture"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1"
bumpalo = {version = "3.14.0", features = ["collections", "allocator-api2"]}
cinder = { path = "../../lib/cinder" }
util = { path = "../../lib/util" }
zero-copy-assets = { path = "../../lib/zero-copy-assets" }
sdl2 = { git = "https://github.com/Rust-SDL2/rust-sdl2", features = [
    "bundled",
    "raw-window-handle",
] }
math = { git = "https://github.com/ArthurKValladares/Yet-Another-Math-Lib" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
zune-png = "0.2.0"
render_graph = { path = "../../lib/render_graph" }

[build-dependencies]
home = "0.5.3"
rust-shader-tools = { git = "https://github.com/ArthurKValladares/Rust-Shader-Tools" }
