[package]
name = "hello-triangle"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1"
cinder = {path = "../../lib/cinder"}
image = "0.24.3"
math = { git = "https://github.com/ArthurKValladares/Yet-Another-Math-Lib" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
sdl2 = { git = "https://github.com/Rust-SDL2/rust-sdl2", features = ["bundled", "raw-window-handle"] }
util = {path = "../../lib/util"}
render_graph = {path = "../../lib/render_graph"}

[build-dependencies]
home = "0.5.3"
rust-shader-tools = { git = "https://github.com/ArthurKValladares/Rust-Shader-Tools" }